### PR TITLE
Update base62.h for pg16 compatibility

### PR DESCRIPTION
**Pull request by ridvankorkmaz**
same issue as ipath has, so I add the same piece of include here.

/*
 * pg >= 16 reorganized the toastable header files
 * https://github.com/postgres/postgres/commit/d952373a987bad331c0e499463159dd142ced1ef
 * to ensure cross version compatibility we do a bit of a hack here */ #ifndef SET_VARSIZE
#include "varatt.h"
#endif

### CODE REVIEW

**Review by za-arthur — CHANGES_REQUESTED** [review]
Thank you. Can you add Postgres 16 into the tests?
https://github.com/adjust/pg-base62/blob/c2b6763baede659560fde02692c336069548a6d7/.github/workflows/main.yml#L14

**Comment by ridvankorkmaz** [comment]
Thanks @za-arthur for review and suggestion, I added 16 test but failed,
It is compiled on 15 but failed on 16 due to changes in PostgreSQL code, I have to investigate and update here.

This is the function `Abs` that is not in 16 version, 
https://github.com/adjust/pg-base62/blob/98e1bd92514d1dcfb59e67b4be1e3cfd08db37e3/src/hugebase62.c#L172

**Comment by ridvankorkmaz** [comment]
pg16 test failed, next week I will take care of it.

**Comment by ridvankorkmaz** [comment]
issue is that, `Abs` function has been removed at this [commit](https://github.com/postgres/postgres/commit/a699b7a7aa9f34c19aa7632b3f037f24c8ee7720) from PostgreSQL, and they have discussion about to remove `Abs` and use` abs/fabs`. I also used `abs` when I compile on my local Mac, but it gives warning this time, I am not sure to follow which way yet.


```
src/hugebase62.c:172:17: warning: absolute value function 'abs' given an argument of type 'hugebase62' (aka '__int128') but has parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
        hugebase62      m = abs(*c);
```

**Comment by za-arthur** [comment]
Indeed, good finding. I don't know why I used the macros `Abs`. It is possible to use `abs` C function instead. But after fixing it, I see another error:

```
src/hugebase62.c:262:42: warning: implicit declaration of function ‘VARSIZE_ANY_EXHDR’ [-Wimplicit-function-declaration]
  262 |         int                     nbytes = VARSIZE_ANY_EXHDR(value);
```

It can be fixed by adding into `hugebase62.c`:

```
#if PG_VERSION_NUM >= 160000
#include "varatt.h"
#endif
```

**Review by ridvankorkmaz — COMMENTED** [review]
just ok.

**Pull request merged**
